AllCops:
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

Style/StringLiterals:
  EnforcedStyle: double_quotes
